// Generated by Wrangler by running `wrangler types`

interface Env {
  ACCESS_GROUP_ID: "62174ffa-cecf-47c5-ba03-b7928329293b";
  CLOUDFLARE_ACCOUNT_ID: "b1caf8cf81b661ff2c8de602eea21c63";
  CLOUDFLARE_API_TOKEN: string;
}
